error_on_line_overflow = true
error_on_unformatted = true
fn_args_layout = 'Compressed'
group_imports = 'StdExternalCrate'
imports_granularity = 'Crate'
match_block_trailing_comma = true
max_width = 120
newline_style = 'Unix'
normalize_comments = true
reorder_impl_items = true
report_fixme = 'Always'
report_todo = 'Always'
tab_spaces = 2
trailing_comma = 'Never'
use_small_heuristics = 'Max'
use_field_init_shorthand = true
use_try_shorthand = true
where_single_line = true
wrap_comments = true
